### ISSUE TITLE
error in walk.py 

### ISSUE THREAD

**Issue by mcaralimarad** [MitPandya/Human-Action-Recognition-and-Video-Classification-using-SVM-and-Deep-CNN-#2]
when i tried to execute walk.py  i am getting this error

OpenCV Error: Assertion failed (_mean.size() == mean_sz) in operator(), file /build/opencv-SviWsf/opencv-2.4.9.1+dfsg/modules/core/src/matmul.cpp, line 2873
Traceback (most recent call last):
  File "/home/aralimarad/Documents/LiClipse Workspace/humanActivityRecog/Human-Action-Recognition-and-Video-Classification-using-SVM-and-Deep-CNN--master/walk.py", line 47, in <module>
    m,v = cv2.PCACompute(xarr, mean = np.array([]))
cv2.error: /build/opencv-SviWsf/opencv-2.4.9.1+dfsg/modules/core/src/matmul.cpp:2873: error: (-215) _mean.size() == mean_sz in function operator()

so i tried to check the frame. yes frame exist and when tried to display the values of the image its showing contents as zero but size of it displayed properly.
dont know whats wrong with code.

**Comment by MitPandya** [comment]
Hi there, can you try to print values of xarr  just before cv2.PCACompute, this happened in the older version of cv2 maybe you can try reinstalling or upgrading it. More solutions here https://stackoverflow.com/questions/8567704/opencv-pca-compute-in-python

**Comment by mcaralimarad** [comment]
installing new version helped me to get result. Thank you
