### ISSUE TITLE
Feels some step(s) or info went missing

### ISSUE THREAD

**Issue by prosunnysanjay** [MitPandya/Human-Action-Recognition-and-Video-Classification-using-SVM-and-Deep-CNN-#5]
Couldn't Find python **cifar10/cifar10_train**. in the repository, neither any folder **tmp/cifar10-data** was created. Can you help me out by describing them or links to understand it.

Academic purpose.

**Comment by MitPandya** [comment]
Hi, Thanks for pointing out, I have updated readme file alternatively please refer to this link https://github.com/tensorflow/models/tree/master/tutorials/image/cifar10 .
All you need to do is train this model on your custom created data as mentioned in readme steps.
